# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mverzilo <mverzilo@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/11/18 10:24:34 by mverzilo          #+#    #+#              #
#    Updated: 2025/11/20 16:32:08 by mverzilo         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME		:= libft.a

CC			:= cc
CFLAGS		:= -Wall -Wextra -Werror

AR			:= ar rcs
RM			:= rm -f

SRCS    := ft_isalpha.c ft_isdigit.c ft_isalnum.c ft_isascii.c \
           ft_isprint.c ft_strlen.c ft_memset.c ft_bzero.c \
           ft_memcpy.c ft_memmove.c ft_strlcpy.c ft_strlcat.c \
           ft_toupper.c ft_tolower.c ft_strchr.c ft_strrchr.c \
           ft_strncmp.c ft_memchr.c ft_memcmp.c ft_strnstr.c \
           ft_atoi.c ft_calloc.c ft_strdup.c ft_substr.c \
           ft_strjoin.c ft_strtrim.c ft_split.c ft_itoa.c \
           ft_strmapi.c ft_striteri.c ft_putchar_fd.c \
           ft_putstr_fd.c ft_putendl_fd.c ft_putnbr_fd.c\
           ft_printf.c  ft_printf_utils.c  ft_putchar.c\
           ft_putnbr.c  ft_putstr.c

B_SRCS  := ft_lstnew.c ft_lstadd_front.c ft_lstsize.c \
           ft_lstlast.c ft_lstadd_back.c ft_lstdelone.c \
           ft_lstclear.c ft_lstiter.c ft_lstmap.c

OBJS		:= $(SRCS:%.c=%.o)
B_OBJS		:= $(B_SRCS:%.c=%.o)

.PHONY: all clean fclean re bonus norm

all: $(NAME)

$(NAME): $(OBJS)
	$(AR) $@ $^

bonus: $(OBJS) $(B_OBJS)
	$(AR) $(NAME) $(B_OBJS)

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	$(RM) $(OBJS) $(B_OBJS)

fclean: clean
	$(RM) $(NAME)

re: fclean all
